import type { MockShopItem, MockShopUser } from "@/types/shop";

const mockUsers: MockShopUser[] = [
	{
		id: "u1",
		username: "Kendrick",
		avatarUrl: "https://i.pravatar.cc/150?u=1",
		badges: ["star", "verified"],
	},
	{
		id: "u2",
		username: "Almond Neko",
		avatarUrl: "https://i.pravatar.cc/150?u=2",
		badges: ["leaf"],
	},
	{
		id: "u3",
		username: "UniqueOly",
		avatarUrl: "https://i.pravatar.cc/150?u=3",
		badges: ["fire"],
	},
	{
		id: "u4",
		username: "salmon",
		avatarUrl: "https://i.pravatar.cc/150?u=4",
		badges: ["star"],
	},
	{
		id: "u5",
		username: "mobietin",
		avatarUrl: "https://i.pravatar.cc/150?u=5",
		badges: ["verified"],
	},
	{
		id: "u6",
		username: "TabbythaNyx",
		avatarUrl: "https://i.pravatar.cc/150?u=6",
		badges: ["star", "verified"],
	},
];

export const MOCK_SHOP_ITEMS: MockShopItem[] = [
	// Original Designs (c1)
	{
		id: "i1",
		categoryId: "c1",
		title: "Big Bunny Adopt Batch",
		description: "",
		price: 36.77,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i1/400/300",
		images: [],
		badges: ["1 of a kind"],
		author: mockUsers[0],
		salesCount: 14,
		rating: 5.0,
	},
	{
		id: "i2",
		categoryId: "c1",
		title: "Super Squishy Axolotl 03",
		description: "",
		price: 55.15,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i2/400/300",
		images: [],
		badges: ["1 of a kind"],
		author: mockUsers[1],
		salesCount: 1,
		rating: 5.0,
	},
	{
		id: "i3",
		categoryId: "c1",
		title: "Adopt animals cute [commercial use] V.2",
		description: "",
		price: 62.51,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i3/400/300",
		images: [],
		badges: ["1 of a kind"],
		author: mockUsers[2],
		salesCount: 1,
		rating: 5.0,
	},
	{
		id: "i4",
		categoryId: "c1",
		title: "$7 | Duo scrap designs",
		description: "",
		price: 25.74,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i4/400/300",
		images: [],
		badges: ["1 of a kind"],
		author: mockUsers[3],
		salesCount: 1,
		rating: 5.0,
	},
	{
		id: "i5",
		categoryId: "c1",
		title: "Formal Rabbit Adopts",
		description: "",
		price: 91.92,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i5/400/300",
		images: [],
		badges: [],
		author: mockUsers[4],
		salesCount: 3,
		rating: 5.0,
	},
	{
		id: "i6",
		categoryId: "c1",
		title: "Pom Pom Adopt Batch 6",
		description: "",
		price: 1.84,
		currencyCode: "PLN",
		originalPrice: 3.68,
		discountPct: 50,
		coverImage: "https://picsum.photos/seed/i6/400/300",
		images: [],
		badges: [],
		author: mockUsers[5],
		salesCount: 1,
		rating: 5.0,
	},

	// 2D Avatars (c2)
	{
		id: "i7",
		categoryId: "c2",
		title: "PRISM Customizable Vtuber Model",
		description: "",
		price: 496.31,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i7/400/300",
		images: [],
		badges: [],
		author: mockUsers[0],
		salesCount: 5851,
		rating: 5.0,
	},
	{
		id: "i8",
		categoryId: "c2",
		title: "2wintails Customizable model",
		description: "",
		price: 490.47,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i8/400/300",
		images: [],
		badges: [],
		author: mockUsers[1],
		salesCount: 3068,
		rating: 5.0,
	},
	{
		id: "i9",
		categoryId: "c2",
		title: "Isa's Customizable Vtuber Model",
		description: "",
		price: 294.15,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i9/400/300",
		images: [],
		badges: [],
		author: mockUsers[2],
		salesCount: 803,
		rating: 5.0,
	},
	{
		id: "i10",
		categoryId: "c2",
		title: "LizMeta Customizable Vtuber Model 1.03",
		description: "",
		price: 474.32,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i10/400/300",
		images: [],
		badges: [],
		author: mockUsers[3],
		salesCount: 3026,
		rating: 5.0,
	},
	{
		id: "i11",
		categoryId: "c2",
		title: "Biga Chibi Customizable Model",
		description: "",
		price: 58.83,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i11/400/300",
		images: [],
		badges: [],
		author: mockUsers[4],
		salesCount: 375,
		rating: 5.0,
	},
	{
		id: "i12",
		categoryId: "c2",
		title: "Customizable Vtuber Model Hachimi Chibi",
		description: "",
		price: 11.03,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i12/400/300",
		images: [],
		badges: [],
		author: mockUsers[5],
		salesCount: 6277,
		rating: 5.0,
	},

	// Concept Art (c3)
	{
		id: "i13",
		categoryId: "c3",
		title: "Sci-Fi Environment Concepts Vol.1",
		description: "",
		price: 120.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i13/400/300",
		images: [],
		badges: ["bestseller"],
		author: mockUsers[1],
		salesCount: 154,
		rating: 4.9,
	},
	{
		id: "i14",
		categoryId: "c3",
		title: "Fantasy Weapon Blueprints",
		description: "",
		price: 45.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i14/400/300",
		images: [],
		badges: [],
		author: mockUsers[3],
		salesCount: 89,
		rating: 4.8,
	},

	// Illustration (c4)
	{
		id: "i15",
		categoryId: "c4",
		title: "Cozy Room Background Pack",
		description: "",
		price: 80.5,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i15/400/300",
		images: [],
		badges: [],
		author: mockUsers[2],
		salesCount: 420,
		rating: 5.0,
	},
	{
		id: "i16",
		categoryId: "c4",
		title: "Lo-Fi Beats Cover Art",
		description: "",
		price: 65.0,
		currencyCode: "PLN",
		originalPrice: 130.0,
		discountPct: 50,
		coverImage: "https://picsum.photos/seed/i16/400/300",
		images: [],
		badges: [],
		author: mockUsers[5],
		salesCount: 12,
		rating: 4.7,
	},

	// Emote / Sticker (c5)
	{
		id: "i17",
		categoryId: "c5",
		title: "10x Twitch Cat Emotes",
		description: "",
		price: 25.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i17/400/300",
		images: [],
		badges: ["trending"],
		author: mockUsers[4],
		salesCount: 1205,
		rating: 5.0,
	},
	{
		id: "i18",
		categoryId: "c5",
		title: "Animated Discord Stickers - Fox Edition",
		description: "",
		price: 40.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i18/400/300",
		images: [],
		badges: [],
		author: mockUsers[0],
		salesCount: 890,
		rating: 4.9,
	},

	// Traditional Art (c6)
	{
		id: "i19",
		categoryId: "c6",
		title: "Watercolor Landscape Scans",
		description: "",
		price: 150.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i19/400/300",
		images: [],
		badges: ["1 of a kind"],
		author: mockUsers[2],
		salesCount: 4,
		rating: 5.0,
	},
	{
		id: "i20",
		categoryId: "c6",
		title: "Graphite Portrait Commissions - Slot",
		description: "",
		price: 300.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i20/400/300",
		images: [],
		badges: [],
		author: mockUsers[1],
		salesCount: 2,
		rating: 5.0,
	},

	// Handcraft (c7)
	{
		id: "i21",
		categoryId: "c7",
		title: "Crochet Pattern: Little Dragon",
		description: "",
		price: 15.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i21/400/300",
		images: [],
		badges: ["bestseller"],
		author: mockUsers[5],
		salesCount: 3042,
		rating: 4.8,
	},
	{
		id: "i22",
		categoryId: "c7",
		title: "Resin Dice Mold Template 3D Print File",
		description: "",
		price: 20.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i22/400/300",
		images: [],
		badges: [],
		author: mockUsers[3],
		salesCount: 56,
		rating: 4.6,
	},

	// Animation (c8)
	{
		id: "i23",
		categoryId: "c8",
		title: "Stream Starting Soon Screen (Animated)",
		description: "",
		price: 85.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i23/400/300",
		images: [],
		badges: [],
		author: mockUsers[0],
		salesCount: 430,
		rating: 4.9,
	},
	{
		id: "i24",
		categoryId: "c8",
		title: "Spine2D Idle Animation Loop",
		description: "",
		price: 120.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i24/400/300",
		images: [],
		badges: [],
		author: mockUsers[4],
		salesCount: 22,
		rating: 5.0,
	},

	// Pixel Art (c9)
	{
		id: "i25",
		categoryId: "c9",
		title: "RPG Maker Tileset: Haunted Forest",
		description: "",
		price: 55.0,
		currencyCode: "PLN",
		coverImage: "https://picsum.photos/seed/i25/400/300",
		images: [],
		badges: ["trending"],
		author: mockUsers[2],
		salesCount: 891,
		rating: 5.0,
	},
	{
		id: "i26",
		categoryId: "c9",
		title: "Pixel UI Asset Pack",
		description: "",
		price: 30.0,
		currencyCode: "PLN",
		originalPrice: 60.0,
		discountPct: 50,
		coverImage: "https://picsum.photos/seed/i26/400/300",
		images: [],
		badges: [],
		author: mockUsers[1],
		salesCount: 1560,
		rating: 4.8,
	},
];
