"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _header_artist_dashboard from './header-artist_dashboard.bones.json'
import _header_user_menu from './header-user_menu.bones.json'

registerBones({
  "header-artist_dashboard": _header_artist_dashboard,
  "header-user_menu": _header_user_menu,
})
