/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MainRouteImport } from './routes/_main'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardForms_templatesRouteImport } from './routes/dashboard/forms_templates'
import { Route as DashboardCommissions_requestsRouteImport } from './routes/dashboard/commissions_requests'
import { Route as MainTosRouteImport } from './routes/_main.tos'
import { Route as MainReleaseNotesRouteImport } from './routes/_main.release-notes'
import { Route as MainPrivacyRouteImport } from './routes/_main.privacy'
import { Route as MainMyRequestsRouteImport } from './routes/_main.my-requests'
import { Route as MainLogoutRouteImport } from './routes/_main.logout'
import { Route as MainUsernameRouteImport } from './routes/_main.$username'
import { Route as MainAuthRouteRouteImport } from './routes/_main.auth/route'
import { Route as MainUsernameTabRouteImport } from './routes/_main.$username/$tab'
import { Route as MainAuthRegisterIndexRouteImport } from './routes/_main.auth/register/index'
import { Route as MainAuthLoginIndexRouteImport } from './routes/_main.auth/login/index'
import { Route as MainAuthForgotIndexRouteImport } from './routes/_main.auth/forgot/index'
import { Route as MainUsernameTabCommissionIdIndexRouteImport } from './routes/_main.$username/$tab/$commissionId/index'
import { Route as MainUsernameTabFolderFolderSlugIndexRouteImport } from './routes/_main.$username/$tab/folder/$folderSlug/index'
import { Route as MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRouteImport } from './routes/_main.$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForms_templatesRoute =
  DashboardForms_templatesRouteImport.update({
    id: '/forms_templates',
    path: '/forms_templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCommissions_requestsRoute =
  DashboardCommissions_requestsRouteImport.update({
    id: '/commissions_requests',
    path: '/commissions_requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const MainTosRoute = MainTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => MainRoute,
} as any)
const MainReleaseNotesRoute = MainReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => MainRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRoute,
} as any)
const MainMyRequestsRoute = MainMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => MainRoute,
} as any)
const MainLogoutRoute = MainLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any)
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameTabRoute = MainUsernameTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => MainUsernameRoute,
} as any)
const MainAuthRegisterIndexRoute = MainAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthLoginIndexRoute = MainAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthForgotIndexRoute = MainAuthForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainUsernameTabCommissionIdIndexRoute =
  MainUsernameTabCommissionIdIndexRouteImport.update({
    id: '/$commissionId/',
    path: '/$commissionId/',
    getParentRoute: () => MainUsernameTabRoute,
  } as any)
const MainUsernameTabFolderFolderSlugIndexRoute =
  MainUsernameTabFolderFolderSlugIndexRouteImport.update({
    id: '/folder/$folderSlug/',
    path: '/folder/$folderSlug/',
    getParentRoute: () => MainUsernameTabRoute,
  } as any)
const MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute =
  MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRouteImport.update({
    id: '/folder/$folderSlug/$subfolderSlug/$postId',
    path: '/folder/$folderSlug/$subfolderSlug/$postId',
    getParentRoute: () => MainUsernameTabRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof MainAuthRouteRouteWithChildren
  '/$username': typeof MainUsernameRouteWithChildren
  '/logout': typeof MainLogoutRoute
  '/my-requests': typeof MainMyRequestsRoute
  '/privacy': typeof MainPrivacyRoute
  '/release-notes': typeof MainReleaseNotesRoute
  '/tos': typeof MainTosRoute
  '/dashboard/commissions_requests': typeof DashboardCommissions_requestsRoute
  '/dashboard/forms_templates': typeof DashboardForms_templatesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$username/$tab': typeof MainUsernameTabRouteWithChildren
  '/auth/forgot/': typeof MainAuthForgotIndexRoute
  '/auth/login/': typeof MainAuthLoginIndexRoute
  '/auth/register/': typeof MainAuthRegisterIndexRoute
  '/$username/$tab/$commissionId/': typeof MainUsernameTabCommissionIdIndexRoute
  '/$username/$tab/folder/$folderSlug/': typeof MainUsernameTabFolderFolderSlugIndexRoute
  '/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId': typeof MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof MainAuthRouteRouteWithChildren
  '/$username': typeof MainUsernameRouteWithChildren
  '/logout': typeof MainLogoutRoute
  '/my-requests': typeof MainMyRequestsRoute
  '/privacy': typeof MainPrivacyRoute
  '/release-notes': typeof MainReleaseNotesRoute
  '/tos': typeof MainTosRoute
  '/dashboard/commissions_requests': typeof DashboardCommissions_requestsRoute
  '/dashboard/forms_templates': typeof DashboardForms_templatesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$username/$tab': typeof MainUsernameTabRouteWithChildren
  '/auth/forgot': typeof MainAuthForgotIndexRoute
  '/auth/login': typeof MainAuthLoginIndexRoute
  '/auth/register': typeof MainAuthRegisterIndexRoute
  '/$username/$tab/$commissionId': typeof MainUsernameTabCommissionIdIndexRoute
  '/$username/$tab/folder/$folderSlug': typeof MainUsernameTabFolderFolderSlugIndexRoute
  '/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId': typeof MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_main/auth': typeof MainAuthRouteRouteWithChildren
  '/_main/$username': typeof MainUsernameRouteWithChildren
  '/_main/logout': typeof MainLogoutRoute
  '/_main/my-requests': typeof MainMyRequestsRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/release-notes': typeof MainReleaseNotesRoute
  '/_main/tos': typeof MainTosRoute
  '/dashboard/commissions_requests': typeof DashboardCommissions_requestsRoute
  '/dashboard/forms_templates': typeof DashboardForms_templatesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_main/$username/$tab': typeof MainUsernameTabRouteWithChildren
  '/_main/auth/forgot/': typeof MainAuthForgotIndexRoute
  '/_main/auth/login/': typeof MainAuthLoginIndexRoute
  '/_main/auth/register/': typeof MainAuthRegisterIndexRoute
  '/_main/$username/$tab/$commissionId/': typeof MainUsernameTabCommissionIdIndexRoute
  '/_main/$username/$tab/folder/$folderSlug/': typeof MainUsernameTabFolderFolderSlugIndexRoute
  '/_main/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId': typeof MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/$username'
    | '/logout'
    | '/my-requests'
    | '/privacy'
    | '/release-notes'
    | '/tos'
    | '/dashboard/commissions_requests'
    | '/dashboard/forms_templates'
    | '/dashboard/services'
    | '/dashboard/'
    | '/$username/$tab'
    | '/auth/forgot/'
    | '/auth/login/'
    | '/auth/register/'
    | '/$username/$tab/$commissionId/'
    | '/$username/$tab/folder/$folderSlug/'
    | '/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/$username'
    | '/logout'
    | '/my-requests'
    | '/privacy'
    | '/release-notes'
    | '/tos'
    | '/dashboard/commissions_requests'
    | '/dashboard/forms_templates'
    | '/dashboard/services'
    | '/'
    | '/dashboard'
    | '/$username/$tab'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/$username/$tab/$commissionId'
    | '/$username/$tab/folder/$folderSlug'
    | '/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'
  id:
    | '__root__'
    | '/_main'
    | '/dashboard'
    | '/_main/auth'
    | '/_main/$username'
    | '/_main/logout'
    | '/_main/my-requests'
    | '/_main/privacy'
    | '/_main/release-notes'
    | '/_main/tos'
    | '/dashboard/commissions_requests'
    | '/dashboard/forms_templates'
    | '/dashboard/services'
    | '/_main/'
    | '/dashboard/'
    | '/_main/$username/$tab'
    | '/_main/auth/forgot/'
    | '/_main/auth/login/'
    | '/_main/auth/register/'
    | '/_main/$username/$tab/$commissionId/'
    | '/_main/$username/$tab/folder/$folderSlug/'
    | '/_main/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forms_templates': {
      id: '/dashboard/forms_templates'
      path: '/forms_templates'
      fullPath: '/dashboard/forms_templates'
      preLoaderRoute: typeof DashboardForms_templatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commissions_requests': {
      id: '/dashboard/commissions_requests'
      path: '/commissions_requests'
      fullPath: '/dashboard/commissions_requests'
      preLoaderRoute: typeof DashboardCommissions_requestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_main/tos': {
      id: '/_main/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof MainTosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/release-notes': {
      id: '/_main/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof MainReleaseNotesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/my-requests': {
      id: '/_main/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MainMyRequestsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/logout': {
      id: '/_main/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof MainLogoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auth': {
      id: '/_main/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof MainAuthRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username/$tab': {
      id: '/_main/$username/$tab'
      path: '/$tab'
      fullPath: '/$username/$tab'
      preLoaderRoute: typeof MainUsernameTabRouteImport
      parentRoute: typeof MainUsernameRoute
    }
    '/_main/auth/register/': {
      id: '/_main/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof MainAuthRegisterIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/auth/login/': {
      id: '/_main/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof MainAuthLoginIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/auth/forgot/': {
      id: '/_main/auth/forgot/'
      path: '/forgot'
      fullPath: '/auth/forgot/'
      preLoaderRoute: typeof MainAuthForgotIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/$username/$tab/$commissionId/': {
      id: '/_main/$username/$tab/$commissionId/'
      path: '/$commissionId'
      fullPath: '/$username/$tab/$commissionId/'
      preLoaderRoute: typeof MainUsernameTabCommissionIdIndexRouteImport
      parentRoute: typeof MainUsernameTabRoute
    }
    '/_main/$username/$tab/folder/$folderSlug/': {
      id: '/_main/$username/$tab/folder/$folderSlug/'
      path: '/folder/$folderSlug'
      fullPath: '/$username/$tab/folder/$folderSlug/'
      preLoaderRoute: typeof MainUsernameTabFolderFolderSlugIndexRouteImport
      parentRoute: typeof MainUsernameTabRoute
    }
    '/_main/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId': {
      id: '/_main/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'
      path: '/folder/$folderSlug/$subfolderSlug/$postId'
      fullPath: '/$username/$tab/folder/$folderSlug/$subfolderSlug/$postId'
      preLoaderRoute: typeof MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRouteImport
      parentRoute: typeof MainUsernameTabRoute
    }
  }
}

interface MainAuthRouteRouteChildren {
  MainAuthForgotIndexRoute: typeof MainAuthForgotIndexRoute
  MainAuthLoginIndexRoute: typeof MainAuthLoginIndexRoute
  MainAuthRegisterIndexRoute: typeof MainAuthRegisterIndexRoute
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthForgotIndexRoute: MainAuthForgotIndexRoute,
  MainAuthLoginIndexRoute: MainAuthLoginIndexRoute,
  MainAuthRegisterIndexRoute: MainAuthRegisterIndexRoute,
}

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
)

interface MainUsernameTabRouteChildren {
  MainUsernameTabCommissionIdIndexRoute: typeof MainUsernameTabCommissionIdIndexRoute
  MainUsernameTabFolderFolderSlugIndexRoute: typeof MainUsernameTabFolderFolderSlugIndexRoute
  MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute: typeof MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute
}

const MainUsernameTabRouteChildren: MainUsernameTabRouteChildren = {
  MainUsernameTabCommissionIdIndexRoute: MainUsernameTabCommissionIdIndexRoute,
  MainUsernameTabFolderFolderSlugIndexRoute:
    MainUsernameTabFolderFolderSlugIndexRoute,
  MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute:
    MainUsernameTabFolderFolderSlugSubfolderSlugPostIdRoute,
}

const MainUsernameTabRouteWithChildren = MainUsernameTabRoute._addFileChildren(
  MainUsernameTabRouteChildren,
)

interface MainUsernameRouteChildren {
  MainUsernameTabRoute: typeof MainUsernameTabRouteWithChildren
}

const MainUsernameRouteChildren: MainUsernameRouteChildren = {
  MainUsernameTabRoute: MainUsernameTabRouteWithChildren,
}

const MainUsernameRouteWithChildren = MainUsernameRoute._addFileChildren(
  MainUsernameRouteChildren,
)

interface MainRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren
  MainUsernameRoute: typeof MainUsernameRouteWithChildren
  MainLogoutRoute: typeof MainLogoutRoute
  MainMyRequestsRoute: typeof MainMyRequestsRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainReleaseNotesRoute: typeof MainReleaseNotesRoute
  MainTosRoute: typeof MainTosRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainUsernameRoute: MainUsernameRouteWithChildren,
  MainLogoutRoute: MainLogoutRoute,
  MainMyRequestsRoute: MainMyRequestsRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainReleaseNotesRoute: MainReleaseNotesRoute,
  MainTosRoute: MainTosRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface DashboardRouteChildren {
  DashboardCommissions_requestsRoute: typeof DashboardCommissions_requestsRoute
  DashboardForms_templatesRoute: typeof DashboardForms_templatesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCommissions_requestsRoute: DashboardCommissions_requestsRoute,
  DashboardForms_templatesRoute: DashboardForms_templatesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
